### ISSUE TITLE
what does the "binary label" mentioned in the code mean?

### ISSUE THREAD

**Issue by zj19921221** [zxhuang1698/interpretability-by-parts#5]
hi zxhuang
i  have two quenstions：
(0)when i read the code in 'train.py' I am confused about the "binary label"?
if the num_classes is 3; the binary label is the same as one_hot label ? "001 010 100"? or just  show as   "00 01 10"?

(1)Do you think it will be useful to apply the method in the article to the TWO_classes classification?
looking forward your reply!
thanks a lot!

**Comment by zxhuang1698** [comment]
Hi, thanks for your interest. 

0) For CelebA, every face is annotated with 40 labels. Each label is denoting whether a certain attribute exist or not. For example, whether a certain face shows the attribute "smiling". So it can only be binary as it's annotated so. If the num_classes = 3, it does not mean every attribute has three possible values, it means we have three attributes instead. 

1) I haven't really tried this but I think it depends. For CelebA, the label is indeed binary. But there are 40 attributes and they relate to different regions in a face. Accurately classifying these attributes implicitly encourages the network to look at different parts for each attribute. But if we only have one such binary label, for example, "black hair", the network might only rely on the hair region to make its decision. Thus it may not lead to meaningful segmentation on other regions if you set the desired number of parts to be 3 or even more.
