### ISSUE TITLE
The importance of postblock?

### ISSUE THREAD

**Issue by tian0810** [zxhuang1698/interpretability-by-parts#7]
Great work! After I remove the postblock in your code, the eval_acc only decreases a little(87.0%-->85.9%),eval_interp(12.0%-->14.4%). However, the visualization of assignment map become very blurry ，so why did it happen? And what's the effect of the postblock? Thanks!

**Comment by zxhuang1698** [comment]
It's simply non-linear transformation over the VLAD feature. Directly optimizing an FC layer on the weighted combination of VLAD feature might not be easy due to varying variance.
