### ISSUE TITLE
evaluation for cub dataset

### ISSUE THREAD

**Issue by AmeenAli** [zxhuang1698/interpretability-by-parts#8]
hello,
in the paper there are three splits for the evaulation on cub dataset :
cub-001, cub-002 , cub-002, what are these stands for and how can i run on each split?

**Comment by zxhuang1698** [comment]
They mean different categories. Please take a look at Sec 4.2, "Localization Results (Interpretability)" in the paper for detailed description. You can write an if-condition by label in the evaluation script yourself to use samples only from a certain category and calculate the single-category localization error.
